name: Extract and Deduplicate Text

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  extract_data:  # 使用英文标识符
    name: 提取并去重数据  # 这里可以使用中文显示名称
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出仓库
      uses: actions/checkout@v3
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: 运行提取脚本
      run: python extract_text.py
      
    - name: 提交并推送结果
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add extract_text.py 提取结果.txt
        git commit -m "更新提取结果" || echo "没有变化需要提交"
        git push
