name: 提取电视频道名称

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  extract_channels:
    name: 提取并处理频道列表
    runs-on: ubuntu-latest

    # 添加权限设置
    permissions:
      contents: write # 允许工作流写入内容解决403问题
      
    steps:
    - name: 检出仓库
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: 运行提取脚本
      run: python extract_text.py
      
    - name: 提交并推送结果
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add extract_text.py 频道列表.txt
        git commit -m "自动更新频道列表 [skip ci]" || echo "没有变化需要提交"
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
